default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: Aman132091@
  host: localhost

development:
  <<: *default
  database: civic_fund_development

test:
  <<: *default
  database: civic_fund_test

production:
  <<: *default
  database: civic_fund_production
  username: postgres
  password: Aman132091@